### ISSUE TITLE
[HW] DBTABLE

### ISSUE THREAD

**Issue by shw7349** [erstkwak/project-jsp#11]
CREATE TABLE MAP 
(   IDX         NUMBER(10,0) PRIMARY KEY,
    TITLE       VARCHAR2(100),
    ADDR        VARCHAR2(100),
    GU          VARCHAR2(20),
    TEL         VARCHAR2(20),
    GYEONGDO    VARCHAR2(50),
    WIDO        VARCHAR2(50)
);
----데이터 입력----

INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '고투 서면점' , '부산 부산진구 중앙대로 686 경암빌딩 2층' , '진구' ,'051-805-5001' , '35.153874926847095', '129.0597185255461');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '엠바디 서면3호점' , '부산 부산진구 중앙대로 712-1 4층' , '진구' ,' ' , '35.156331473417595', '129.059401904223');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '감성피트니스 서면2호점' , '부산 부산진구 서전로 25 이오스프라자 6층' , '진구' ,' ' , '35.156340387924814' , '129.05940761538764');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '미라클짐' , '부산 부산진구 중앙대로691번길 44 지하1층' , '진구' ,'051-715-8788' , '35.15457539658614', '129.0566803191213');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '동천헬스' , '부산 부산진구 동천로 112' , '진구' ,'051-000-0000' , '35.15855742347552', '129.0625743945836');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '오타쿠짐' , '부산 부산진구 서전로37번길 18 지하 1층' , '진구' ,'051-817-0059' , '35.15855133248546', '129.06398977304633');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '코미짐' , '부산 부산진구 부전로 61 3층' , '진구' ,'051-803-5512' , '35.155457937402176', '129.0547247062656');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , 'PK피트니스&PT ' , '부산 부산진구 가야대로 785 인제메티컬센터 B동 11층' , '진구' ,'051-818-1006' , '35.15796462338424', '129.05755845885892');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '베스트피트니스 서면점  ' , '부산 부산진구 서전로10번길 61 쥬디스태화신관 7층' , '진구' ,'051-817-4447' , '35.155130197032776', '129.0602247437582');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '더짐' , '부산 부산진구 중앙대로702번길 50' , '진구' ,'051-802-3366' , '35.155240360757865', '129.06182679002984');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '토마토휘트니스 동래점' , '부산 동래구 명륜로129번길 20 우성빌딩 3층' , '동래구' ,'051-555-7621' , '35.20522582922368', '129.08115108727412');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '멋짐휘트니스 동래점 ' , '부산 동래구 명륜로103번길 8 4, 5층' , '동래구' ,'051-558-8689' , '35.202963260036114', '129.08276215601416');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '조아짐PT 동래본점' , '부산 동래구 명륜로112번가길 51 3층' , '동래구' ,'070-7721-9696' , '35.20611409618762', '129.08307870014562');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '토마토휘트니스 사직점' , '부산 동래구 여고북로 200 2층' , '동래구' ,'051-555-762' , '35.20252503321073', '129.07548560748174');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '플렉스짐' , '부산 동래구 아시아드대로 224 대한메디칼센터 5,6층' , '동래구' ,'051-502-2777' , '35.203640026795576', '129.06720275449504');
INSERT INTO MAP
VALUES ( MAP_SEQ.NEXTVAL , '' , '' , '연제구' ,'' , '');

----자동으로 IDX 증가----
CREATE SEQUENCE MAP_SEQ 
        START WITH 1 
        INCREMENT BY 1;

**Comment by ghost** [comment]
데이터 삽입 시 에러 뜨시는 분은 Insert 문 위 아래에 SET DEFINE OFF와 SET DEFINE ON 추가해서 실행하세요.
